(defun genderage (gen age)
  (cond ((equal age 'adult)
         (cond ((or (equal gen 'man) (equal gen 'woman)) 'manwoman)
               (t 'wackbathrooms)
         )
        )
        ((equal age 'child)
         (cond ((or (equal gen 'boy) (equal gen 'girl)) 'boygirl)
               (t 'wackbathrooms)
         )
        )
        (t 'wackybathrooms)
  )
)
