(defun rocksoff (player1 player2)
  (defun beats (sign)
    (cond ((equal sign 'scissors) 'paper)
          ((equal sign 'paper) 'rock)
          ((equal sign 'rock) 'scissors)
          (t 'no-matches-found))
    )
  (cond ((equal player1 player2) 'stalemate)
        ((equal (beats player1) player2) 'player1-wins)
        ((equal (beats player2) player1) 'player2-wins)
        (t 'unrecognized-input))
)
