(setf b 'B)
(setf o 'O)
(setf x 'X)
(setf d 'D)
(setf r 'R)

(defun indexof (thisin listin)
 (if (member thisin listin)
    (- (length listin) (length (member thisin listin)))
    ()
 )
)

(defun announce (int baser)
  (setf basers (list 'B 'O 'X 'D 'R))
  (setf basernames (list "binary" "octal" "hexadecimal" "decimal" "annunciator" ))
  (setf basername (string (nth (indexof baser basers) basernames)))
  (setf bassist (string baser))
  (setf baserstring (concatenate 'string "This is what ~D looks like in ~A: ~" bassist))
  (format nil baserstring int basername int)
)
