(defun lispload (invalue)
  (defvar mypath "c\:\/users\/geoseph\/documents\/my_git_repos\/lisp-notebook\/lisp-notebook\/")
  (defvar fullpath (concatenate 'string mypath invalue "\.lisp"))
  (load fullpath)
)
