(defun revcalc (intlist)
  (setq i 0)
  (setq track 0)
  (setq greatest 0)
  (defvar resttotal 0)
  (defvar storeresttotal 0)
  (defvar leastlist ())
  (loop for int in intlist do
    (setq track 0)
    (incf i)
    (loop for other in intlist do
      (if (> int other) (incf track))
    )
    (if (equal track (- (length intlist) 1)) (setq greatest int))
  )
  (print "top:")
  (print greatest)
  (loop for intagain in intlist do
    (setq storeresttotal resttotal)
    (if (not (equal intagain greatest)) (setq resttotal (+ storeresttotal intagain)))
  )
  (print "resttotal:")
  (print resttotal)
)
