(setf num-eng-span
  '((cero zero)
    (one uno)
    (two dos)
    (three tres)
    (four cuatro)
    (five cinco)
    (six seis)
    (seven siete)
    (eight ocho)
    (nine nueve)
   )
)

(setf rnum-eng-span
'((cero . zero)
  (one . uno)
  (two . dos)
  (three . tres)
  (four . cuatro)
  (five . cinco)
  (six . seis)
  (seven . siete)
  (eight . ocho)
  (nine . nueve)
 )
)

(setf qualities
(list
(list 'object0 'mealy 'smooth 'coiled 'sore 'metallic 'metallic 'sorcery)
(list 'object1 'metallic 'boring 'tubby 'metallic 'tough 'cool 'sorcery)
(list 'object2 'old 'stout 'old 'smooth 'spent 'tough 'grail)
(list 'object3 'squat 'tough 'cool 'irridescent 'lustrous 'grey 'sorcery)
(list 'object4 'cool 'succulent 'spent 'stout 'frozen 'irridescent 'gamble)
(list 'object5 'irridescent 'stout 'squat 'succulent 'spent 'mealy 'rubric)
(list 'object6 'tough 'turbid 'succulent 'tough 'lurching 'early 'sorcery)
(list 'object7 'old 'irridescent 'mealy 'tough 'old 'tough 'sorcery)
(list 'object8 'irridescent 'velveteen 'sore 'lustrous 'refractive 'refractive 'rod)
(list 'object9 'irridescent 'gory 'cool 'squat 'velveteen 'spotty 'sorcery)
(list 'object10 'spotty 'gory 'coiled 'cantankerous 'old 'spent 'sceptre)
(list 'object11 'velveteen 'lousy 'tough 'irridescent 'squat 'coiled 'grail)
(list 'object12 'refractive 'metallic 'boring 'grey 'cool 'tough 'anecdote)
(list 'object13 'coiled 'gory 'metallic 'tubby 'smooth 'early 'anecdote)
(list 'object14 'lurching 'boring 'laughable 'laughable 'mealy 'smooth 'grail)
(list 'object15 'spotty 'spent 'tubby 'turbid 'spent 'worthwhile 'repast)
(list 'object16 'frozen 'grey 'smooth 'stout 'spent 'gory 'repast)
(list 'object17 'velveteen 'mealy 'coiled 'refractive 'squat 'succulent 'gamble)
(list 'object18 'cool 'lousy 'lousy 'succulent 'tough 'frozen 'sorcery)
(list 'object19 'laughable 'irridescent 'stout 'tough 'cool 'metallic 'sorcery)
(list 'object20 'grey 'lustrous 'irridescent 'velveteen 'old 'lustrous 'sceptre)
(list 'object21 'smooth 'laughable 'velveteen 'lustrous 'cool 'mealy 'coils)
(list 'object22 'velveteen 'lousy 'stout 'spotty 'stout 'tubby 'gamble)
(list 'object23 'coiled 'irridescent 'smooth 'lurching 'metallic 'tough 'rod)
(list 'object24 'stout 'metallic 'refractive 'spotty 'early 'irridescent 'chalice)
(list 'object25 'spotty 'mealy 'spotty 'cantankerous 'mealy 'spotty 'grail)
(list 'object26 'gory 'gory 'spent 'mealy 'coiled 'lurching 'spoils)
(list 'object27 'mealy 'squat 'refractive 'refractive 'mealy 'cantankerous 'grail)
(list 'object28 'spotty 'turbid 'tubby 'refractive 'succulent 'lustrous 'sceptre)
(list 'object29 'cantankerous 'smooth 'lurching 'boring 'lousy 'frozen 'sceptre)
(list 'object30 'old 'grey 'boring 'early 'gory 'cool 'coils)
(list 'object31 'coiled 'velveteen 'lousy 'spotty 'lurching 'metallic 'gamble)
(list 'object32 'boring 'gory 'spotty 'spent 'smooth 'coiled 'spoils)
(list 'object33 'cool 'old 'spotty 'tubby 'mealy 'frozen 'repast)
(list 'object34 'turbid 'worthwhile 'smooth 'stout 'coiled 'laughable 'chalice)
(list 'object35 'refractive 'metallic 'turbid 'gory 'stout 'spent 'chalice)
(list 'object36 'spent 'boring 'stout 'old 'cool 'old 'coils)
(list 'object37 'tubby 'smooth 'turbid 'tubby 'frozen 'frozen 'chalice)
(list 'object38 'gory 'grey 'old 'gory 'cool 'worthwhile 'coils)
(list 'object39 'smooth 'old 'metallic 'spotty 'frozen 'frozen 'rod)
(list 'object40 'sore 'spent 'succulent 'refractive 'lurching 'cantankerous 'coils)
(list 'object41 'lustrous 'lurching 'succulent 'cantankerous 'stout 'lurching 'sceptre)
(list 'object42 'lurching 'turbid 'lousy 'mealy 'grey 'squat 'chalice)
(list 'object43 'grey 'lousy 'refractive 'stout 'coiled 'lurching 'rod)
(list 'object44 'lurching 'old 'irridescent 'grey 'spotty 'irridescent 'grail)
(list 'object45 'frozen 'lustrous 'turbid 'grey 'lustrous 'cantankerous 'rubric)
(list 'object46 'lustrous 'worthwhile 'spotty 'succulent 'squat 'tubby 'rubric)
(list 'object47 'lurching 'tubby 'cool 'stout 'lousy 'spotty 'sceptre)
(list 'object48 'mealy 'succulent 'metallic 'old 'mealy 'succulent 'grail)
(list 'object49 'spotty 'squat 'old 'squat 'spotty 'squat 'repast)
(list 'object50 'coiled 'mealy 'lousy 'smooth 'cantankerous 'cool 'undefined)
(list 'object51 'squat 'metallic 'tough 'spotty 'mealy 'refractive 'coils)
(list 'object52 'grey 'cool 'velveteen 'coiled 'gory 'cantankerous 'rod)
(list 'object53 'cool 'squat 'laughable 'mealy 'sore 'lustrous 'spoils)
(list 'object54 'spent 'old 'turbid 'coiled 'boring 'turbid 'rod)
(list 'object55 'old 'velveteen 'irridescent 'succulent 'refractive 'stout 'undefined)
(list 'object56 'frozen 'metallic 'cool 'lurching 'coiled 'lousy 'rod)
(list 'object57 'smooth 'boring 'cool 'lurching 'sore 'smooth 'spoils)
(list 'object58 'laughable 'stout 'gory 'frozen 'stout 'early 'coils)
(list 'object59 'worthwhile 'worthwhile 'boring 'tubby 'worthwhile 'stout 'spoils)
(list 'object60 'old 'spotty 'spotty 'laughable 'stout 'stout 'rubric)
(list 'object61 'mealy 'irridescent 'velveteen 'succulent 'frozen 'turbid 'sceptre)
(list 'object62 'cantankerous 'tubby 'tough 'boring 'succulent 'lustrous 'chalice)
(list 'object63 'coiled 'gory 'coiled 'turbid 'irridescent 'stout 'coils)
(list 'object64 'irridescent 'coiled 'laughable 'grey 'gory 'lousy 'repast)
(list 'object65 'stout 'cool 'velveteen 'laughable 'mealy 'turbid 'anecdote)
(list 'object66 'tubby 'irridescent 'velveteen 'squat 'lousy 'frozen 'undefined)
(list 'object67 'spent 'irridescent 'boring 'cantankerous 'mealy 'mealy 'repast)
(list 'object68 'frozen 'spotty 'early 'worthwhile 'spent 'turbid 'gamble)
(list 'object69 'laughable 'turbid 'spotty 'velveteen 'gory 'irridescent 'chalice)
(list 'object70 'velveteen 'succulent 'spotty 'mealy 'lousy 'grey 'rod)
(list 'object71 'metallic 'coiled 'frozen 'sore 'laughable 'refractive 'anecdote)
(list 'object72 'turbid 'spent 'spent 'tough 'frozen 'cantankerous 'coils)
(list 'object73 'tubby 'gory 'turbid 'smooth 'cantankerous 'velveteen 'anecdote)
(list 'object74 'mealy 'lousy 'gory 'sore 'spent 'lustrous 'chalice)
(list 'object75 'metallic 'spent 'worthwhile 'tough 'velveteen 'smooth 'gamble)
(list 'object76 'lustrous 'metallic 'laughable 'worthwhile 'squat 'early 'anecdote)
(list 'object77 'refractive 'lousy 'worthwhile 'velveteen 'worthwhile 'old 'repast)
(list 'object78 'cool 'stout 'irridescent 'cantankerous 'coiled 'lustrous 'grail)
(list 'object79 'gory 'sore 'frozen 'old 'sore 'stout 'rubric)
(list 'object80 'succulent 'tubby 'tough 'tubby 'velveteen 'velveteen 'spoils)
(list 'object81 'tough 'lustrous 'velveteen 'grey 'lurching 'squat 'coils)
(list 'object82 'refractive 'grey 'tough 'grey 'squat 'cool 'sceptre)
(list 'object83 'tubby 'gory 'spotty 'lustrous 'spotty 'laughable 'gamble)
(list 'object84 'spent 'tubby 'worthwhile 'tough 'lousy 'gory 'sorcery)
(list 'object85 'cantankerous 'worthwhile 'grey 'worthwhile 'mealy 'old 'gamble)
(list 'object86 'coiled 'stout 'old 'succulent 'cantankerous 'spent 'sceptre)
(list 'object87 'worthwhile 'turbid 'refractive 'cool 'tough 'stout 'spoils)
(list 'object88 'laughable 'gory 'spent 'metallic 'cantankerous 'velveteen 'sceptre)
(list 'object89 'stout 'laughable 'tubby 'smooth 'frozen 'smooth 'sorcery)
(list 'object90 'tubby 'early 'boring 'gory 'early 'grey 'sorcery)
(list 'object91 'turbid 'squat 'irridescent 'gory 'gory 'grey 'anecdote)
(list 'object92 'coiled 'boring 'tough 'coiled 'frozen 'cool 'sorcery)
(list 'object93 'mealy 'irridescent 'tubby 'frozen 'worthwhile 'succulent 'gamble)
(list 'object94 'cantankerous 'lurching 'early 'mealy 'velveteen 'cool 'sorcery)
(list 'object95 'frozen 'mealy 'cantankerous 'tough 'tough 'old 'sorcery)
(list 'object96 'tough 'tubby 'refractive 'spent 'velveteen 'sore 'spoils)
(list 'object97 'velveteen 'old 'coiled 'irridescent 'early 'refractive 'gamble)
(list 'object98 'boring 'lousy 'succulent 'irridescent 'turbid 'coiled 'spoils)
(list 'object99 'sore 'smooth 'metallic 'coiled 'spotty 'cool 'rubric)
(list 'object100 'lurching 'lurching 'metallic 'metallic 'tubby 'frozen 'gamble)
(list 'object101 'velveteen 'tough 'squat 'old 'coiled 'cool 'anecdote)
(list 'object102 'succulent 'succulent 'worthwhile 'spent 'stout 'metallic 'coils)
(list 'object103 'velveteen 'boring 'boring 'lurching 'cool 'tubby 'sorcery)
(list 'object104 'tough 'old 'early 'laughable 'cantankerous 'early 'repast)
(list 'object105 'coiled 'tough 'lustrous 'early 'tough 'lustrous 'rubric)
(list 'object106 'lurching 'squat 'refractive 'coiled 'cantankerous 'mealy 'rod)
(list 'object107 'squat 'mealy 'mealy 'cool 'cool 'irridescent 'rod)
(list 'object108 'tough 'lousy 'lousy 'velveteen 'grey 'squat 'coils)
(list 'object109 'frozen 'irridescent 'mealy 'tubby 'frozen 'tubby 'anecdote)
(list 'object110 'velveteen 'early 'old 'sore 'boring 'lousy 'anecdote)
(list 'object111 'spent 'coiled 'coiled 'spent 'coiled 'worthwhile 'gamble)
(list 'object112 'cool 'metallic 'spotty 'frozen 'tough 'frozen 'grail)
(list 'object113 'succulent 'tubby 'turbid 'smooth 'metallic 'cantankerous 'gamble)
(list 'object114 'laughable 'cool 'turbid 'spotty 'laughable 'lustrous 'gamble)
(list 'object115 'irridescent 'mealy 'squat 'spent 'spotty 'spotty 'grail)
(list 'object116 'laughable 'lustrous 'worthwhile 'frozen 'succulent 'tubby 'coils)
(list 'object117 'lousy 'tubby 'old 'mealy 'cantankerous 'lurching 'repast)
(list 'object118 'grey 'spent 'worthwhile 'tough 'frozen 'succulent 'repast)
(list 'object119 'grey 'irridescent 'coiled 'metallic 'refractive 'lurching 'repast)
(list 'object120 'velveteen 'cantankerous 'cantankerous 'velveteen 'metallic 'turbid 'sorcery)
(list 'object121 'irridescent 'laughable 'lousy 'grey 'turbid 'succulent 'grail)
(list 'object122 'squat 'grey 'cantankerous 'old 'velveteen 'early 'rod)
(list 'object123 'stout 'cool 'velveteen 'irridescent 'spotty 'lurching 'undefined)
(list 'object124 'succulent 'early 'lustrous 'tubby 'spent 'cool 'rubric)
(list 'object125 'mealy 'smooth 'tubby 'cool 'grey 'spent 'chalice)
(list 'object126 'smooth 'succulent 'tough 'metallic 'lousy 'coiled 'sceptre)
(list 'object127 'coiled 'spent 'gory 'grey 'cantankerous 'metallic 'sceptre)
(list 'object128 'squat 'cantankerous 'velveteen 'irridescent 'refractive 'boring 'rod)
(list 'object129 'turbid 'early 'tough 'worthwhile 'spent 'early 'undefined)
(list 'object130 'tubby 'refractive 'velveteen 'tough 'velveteen 'mealy 'chalice)
(list 'object131 'cool 'smooth 'early 'spotty 'mealy 'tubby 'grail)
(list 'object132 'smooth 'sore 'cantankerous 'refractive 'lustrous 'spotty 'coils)
(list 'object133 'lousy 'frozen 'stout 'worthwhile 'sore 'worthwhile 'undefined)
(list 'object134 'laughable 'lustrous 'grey 'spent 'refractive 'coiled 'chalice)
(list 'object135 'worthwhile 'tubby 'tubby 'tough 'squat 'spent 'gamble)
(list 'object136 'gory 'early 'lousy 'early 'lurching 'mealy 'anecdote)
(list 'object137 'lousy 'grey 'cool 'sore 'grey 'turbid 'gamble)
(list 'object138 'frozen 'frozen 'lustrous 'lurching 'refractive 'velveteen 'coils)
(list 'object139 'velveteen 'metallic 'laughable 'mealy 'smooth 'gory 'undefined)
(list 'object140 'lousy 'lurching 'early 'succulent 'cool 'spent 'grail)
(list 'object141 'cool 'laughable 'coiled 'frozen 'tough 'lurching 'spoils)
(list 'object142 'gory 'tough 'early 'metallic 'laughable 'refractive 'chalice)
(list 'object143 'laughable 'tubby 'stout 'early 'refractive 'grey 'rubric)
(list 'object144 'tubby 'succulent 'frozen 'squat 'squat 'spent 'coils)
(list 'object145 'lousy 'mealy 'metallic 'sore 'grey 'sore 'rod)
(list 'object146 'turbid 'old 'cool 'tough 'mealy 'lousy 'grail)
(list 'object147 'velveteen 'lousy 'grey 'velveteen 'velveteen 'refractive 'sorcery)
(list 'object148 'old 'grey 'tubby 'spotty 'smooth 'spent 'anecdote)
(list 'object149 'cool 'lousy 'squat 'metallic 'squat 'smooth 'sceptre)
(list 'object150 'laughable 'spotty 'refractive 'tubby 'refractive 'cool 'grail)
(list 'object151 'squat 'squat 'mealy 'spotty 'tough 'turbid 'spoils)
(list 'object152 'lustrous 'old 'laughable 'spotty 'gory 'turbid 'sorcery)
(list 'object153 'metallic 'old 'cantankerous 'spotty 'refractive 'gory 'sceptre)
(list 'object154 'spotty 'tough 'metallic 'spotty 'gory 'smooth 'chalice)
(list 'object155 'spent 'squat 'grey 'stout 'boring 'early 'grail)
(list 'object156 'mealy 'metallic 'lustrous 'metallic 'squat 'lousy 'sceptre)
(list 'object157 'old 'irridescent 'tough 'lustrous 'laughable 'tough 'anecdote)
(list 'object158 'lurching 'cool 'lustrous 'frozen 'turbid 'spotty 'repast)
(list 'object159 'tough 'spotty 'cool 'succulent 'spent 'spent 'spoils)
(list 'object160 'cool 'refractive 'laughable 'irridescent 'lustrous 'cool 'undefined)
(list 'object161 'coiled 'velveteen 'gory 'frozen 'gory 'refractive 'undefined)
(list 'object162 'lousy 'tough 'tough 'frozen 'coiled 'mealy 'spoils)
(list 'object163 'worthwhile 'sore 'succulent 'lousy 'turbid 'boring 'undefined)
(list 'object164 'frozen 'mealy 'velveteen 'frozen 'gory 'sore 'anecdote)
(list 'object165 'succulent 'stout 'tubby 'tubby 'lousy 'refractive 'spoils)
(list 'object166 'spent 'boring 'worthwhile 'stout 'tough 'refractive 'repast)
(list 'object167 'grey 'stout 'cool 'succulent 'tough 'squat 'undefined)
(list 'object168 'irridescent 'squat 'mealy 'irridescent 'spotty 'velveteen 'grail)
(list 'object169 'worthwhile 'squat 'cantankerous 'grey 'irridescent 'mealy 'anecdote)
(list 'object170 'squat 'tubby 'gory 'lurching 'laughable 'lurching 'sorcery)
(list 'object171 'cool 'turbid 'gory 'lousy 'boring 'mealy 'coils)
(list 'object172 'early 'succulent 'cool 'tubby 'spotty 'tough 'anecdote)
(list 'object173 'tubby 'cantankerous 'lurching 'boring 'cantankerous 'boring 'repast)
(list 'object174 'spotty 'cantankerous 'stout 'worthwhile 'metallic 'succulent 'chalice)
(list 'object175 'laughable 'sore 'metallic 'spent 'coiled 'velveteen 'rubric)
(list 'object176 'cantankerous 'lustrous 'stout 'worthwhile 'gory 'tough 'rubric)
(list 'object177 'refractive 'cool 'old 'tough 'early 'metallic 'grail)
(list 'object178 'succulent 'tough 'mealy 'cool 'velveteen 'metallic 'anecdote)
(list 'object179 'succulent 'coiled 'irridescent 'frozen 'tough 'early 'repast)
(list 'object180 'smooth 'mealy 'irridescent 'gory 'cool 'smooth 'repast)
(list 'object181 'lurching 'worthwhile 'frozen 'early 'tubby 'velveteen 'chalice)
(list 'object182 'grey 'old 'velveteen 'cantankerous 'worthwhile 'tubby 'rubric)
(list 'object183 'gory 'gory 'turbid 'lustrous 'lousy 'boring 'grail)
(list 'object184 'frozen 'lousy 'tough 'lustrous 'squat 'lousy 'sceptre)
(list 'object185 'lousy 'squat 'lustrous 'velveteen 'boring 'spotty 'repast)
(list 'object186 'stout 'gory 'spotty 'velveteen 'cantankerous 'frozen 'sceptre)
(list 'object187 'gory 'early 'frozen 'lurching 'succulent 'laughable 'anecdote)
(list 'object188 'lurching 'cool 'laughable 'tough 'stout 'velveteen 'sorcery)
(list 'object189 'lurching 'grey 'spent 'worthwhile 'velveteen 'stout 'sorcery)
(list 'object190 'lurching 'gory 'squat 'smooth 'laughable 'lustrous 'undefined)
(list 'object191 'smooth 'stout 'coiled 'grey 'tubby 'frozen 'anecdote)
(list 'object192 'gory 'frozen 'turbid 'cool 'irridescent 'metallic 'undefined)
(list 'object193 'sore 'metallic 'gory 'laughable 'old 'cantankerous 'anecdote)
(list 'object194 'spent 'boring 'lustrous 'tubby 'boring 'frozen 'spoils)
(list 'object195 'mealy 'refractive 'velveteen 'succulent 'boring 'irridescent 'sceptre)
(list 'object196 'squat 'lousy 'spent 'tubby 'spotty 'metallic 'spoils)
(list 'object197 'turbid 'lustrous 'succulent 'stout 'spotty 'metallic 'anecdote)
(list 'object198 'mealy 'grey 'smooth 'worthwhile 'spent 'grey 'anecdote)
(list 'object199 'lurching 'frozen 'coiled 'mealy 'mealy 'frozen 'coils)
)
)
